name: tourista
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  sizer: ^2.0.15
  url_launcher: ^6.2.4
  video_player: ^2.8.2
  flutter_speed_dial: ^7.0.0
  youtube_player_flutter: ^8.1.2
  flutter_localizations:
        sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/CairoTimeLapse.mp4
    - assets/pyramids.png
    - assets/tourist.png
    - assets/pyramids.mp4
    - assets/cairoTower.mp4
    - assets/KhanElkhalili.mp4
    - assets/GrandMusuem.mp4
    - assets/videowallpaper.jpg
    - assets/placeWallpaper.jpg
    - assets/icons/
flutter_intl:
  enabled: true
