name: tourista
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sizer: ^2.0.15
  video_player: ^2.8.2
  youtube_player_flutter: ^8.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/CairoTimeLapse.mp4
    - assets/pyramids.png
    - assets/tourist.png
    - assets/pyramids.mp4
    - assets/videowallpaper.jpg